import { NextApiRequest, NextApiResponse } from "next";

export default function route(req: NextApiRequest, res: NextApiResponse) {
  res.send([
    {
      id: 2,
      first_name: "Kyler",
      last_name: "Seely",
      grad_year: 2019,
      college: null,
      job: "Internship",
      achievements: [],
    },
    {
      id: 1,
      first_name: "Alexis",
      last_name: "Chen",
      grad_year: 2019,
      college: "UC San Diego",
      job: null,
      achievements: [
        "AP CS A",
        "TSA President",
        "CTE Software Development Pathway",
      ],
    },
    {
      id: 4,
      first_name: "Martin",
      last_name: "Eldredge",
      grad_year: 2020,
      college: "Utah Valley University",
      job: "Internship",
      achievements: ["AP CS P", "CTE Web Development Pathway"],
    },
    {
      id: 5,
      first_name: "Ethan",
      last_name: "Whitaker",
      grad_year: 2020,
      college: null,
      job: "Internship",
      achievements: [],
    },
    {
      id: 6,
      first_name: "Anna",
      last_name: "Xu",
      grad_year: 2020,
      college: null,
      job: null,
      achievements: ["Teaching Assistant"],
    },
    {
      id: 8,
      first_name: "Richard",
      last_name: "Henage",
      grad_year: 2020,
      college: null,
      job: "SpringMicro",
      achievements: ["CTE Web Development Pathway"],
    },
    {
      id: 11,
      first_name: "Allie",
      last_name: "Erdmann",
      grad_year: 2021,
      college: null,
      job: null,
      achievements: ["NCWiT Award"],
    },
    {
      id: 14,
      first_name: "Mitchell",
      last_name: "Schobert",
      grad_year: 2024,
      college: null,
      job: null,
      achievements: ["NCWiT Award"],
    },
    {
      id: 7,
      first_name: "Eric",
      last_name: "Davis",
      grad_year: 2020,
      college: "Utah Valley University",
      job: "UVU PREP TA",
      achievements: [
        "TestOut PC Pro Certificate",
        "CTE Information Technology Pathway",
      ],
    },
    {
      id: 17,
      first_name: "Tait",
      last_name: "Keck",
      grad_year: 2025,
      college: null,
      job: "SpringMicro",
      achievements: [],
    },
    {
      id: 18,
      first_name: "Gabriel",
      last_name: "Johnson",
      grad_year: 2025,
      college: null,
      job: "SpringMicro",
      achievements: [],
    },
    {
      id: 20,
      first_name: "Talan",
      last_name: "Jenkins",
      grad_year: 2023,
      college: null,
      job: null,
      achievements: ["AP CS A", "AP CS P", "CTE Software Development Pathway"],
    },
    {
      id: 13,
      first_name: "Bryson",
      last_name: "Day",
      grad_year: 2022,
      college: null,
      job: null,
      achievements: ["Teaching Assistant", "CTE Software Development Pathway"],
    },
    {
      id: 12,
      first_name: "Abbey",
      last_name: "Kelley",
      grad_year: 2022,
      college: null,
      job: null,
      achievements: [],
    },
    {
      id: 15,
      first_name: "Hailey",
      last_name: "Grimes",
      grad_year: 2022,
      college: null,
      job: "UVU PREP TA",
      achievements: ["Teaching Assistant"],
    },
    {
      id: 21,
      first_name: "Abbey",
      last_name: "Kelley",
      grad_year: 2022,
      college: "Neumont College of CS",
      job: null,
      achievements: [],
    },
    {
      id: 19,
      first_name: "Kaysen",
      last_name: "Hansen",
      grad_year: 2022,
      college: "Neumont College of CS",
      job: null,
      achievements: [],
    },
    {
      id: 3,
      first_name: "Kyler",
      last_name: "Day",
      grad_year: 2020,
      college: "Neumont College of CS",
      job: "SpringMicro",
      achievements: [
        "AP CS A",
        "AP CS P",
        "Region Sterling Scholar",
        "Teaching Assistant",
        "TSA President",
        "CTE Software Development Pathway",
        "CTE Web Development Pathway",
      ],
    },
    {
      id: 9,
      first_name: "Alex",
      last_name: "Bates",
      grad_year: 2021,
      college: "Neumont College of CS",
      job: "SpringMicro",
      achievements: [
        "AP CS P",
        "Teaching Assistant",
        "TSA President",
        "CTE Software Development Pathway",
        "TestOut PC Pro Certificate",
        "CTE Information Technology Pathway",
      ],
    },
    {
      id: 10,
      first_name: "Jendayi",
      last_name: "Retana",
      grad_year: 2021,
      college: "Neumont College of CS",
      job: "SpringMicro",
      achievements: [
        "AP CS P",
        "TestOut PC Pro Certificate",
        "CTE Information Technology Pathway",
        "NCWiT Award",
      ],
    },
    {
      id: 16,
      first_name: "Dallin",
      last_name: "Charbonneau",
      grad_year: 2022,
      college: "Neumont College of CS",
      job: "SpringMicro",
      achievements: [
        "AP CS A",
        "Teaching Assistant",
        "CTE Software Development Pathway",
        "CTE Web Development Pathway",
      ],
    },
    {
      id: 22,
      first_name: "Ryan",
      last_name: "Meeks",
      grad_year: 2023,
      college: "Neumont College of CS",
      job: null,
      achievements: [
        "AP CS A",
        "AP CS P",
        "Region Sterling Scholar",
        "Teaching Assistant",
        "TSA President",
        "CTE Software Development Pathway",
      ],
    },
    {
      id: 23,
      first_name: "Caleb",
      last_name: "Leman",
      grad_year: 2023,
      college: "University of Utah",
      job: "SpringMicro",
      achievements: ["CTE Software Development Pathway"],
    },
  ]);
}
