import { NextApiRequest, NextApiResponse } from "next";

export default function route(req: NextApiRequest, res: NextApiResponse) {
  res.send([
    {
      id: 1,
      title: "Driving Frenzy",
      author: "Talan Jenkins",
      description:
        "You are 16 years old, and would like to get a driver's license. Make your way through the maze using controls north, south, west, east To win the game, collect your driver's license and make it back to the kitchen. HOORAY!",
      url: "https://replit.com/@TalanJenkins/RPG-Java?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 34,
      title: "puprpg.org",
      author: "Kasey Finch",
      description:
        "So good to hear from you. The year of 1988 was difficult but I made it through. I'm sorry I couldn't contact you sooner.  But I can now so I wanted to say my projects name was puprpg.org. I was able to get it running but it was difficult (not rlly). the project is about walking your dog get the leash a treat your dog and don't get caught by laziness. I will contact you later on the result of the project thank you for your time.",
      url: "https://replit.com/@KaseyFinch/rpg-game?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 35,
      title: "Feed Eduardo",
      author: "Gustavo Postigo",
      description:
        "The game is about getting all the food around the map and once you get it all, you need to go to the bathroom, to win the game.",
      url: "https://replit.com/@GustavoPostigo1/Feed-Eduardo?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 36,
      title: "Goooooooooooost",
      author: "Bryan Mellor",
      description:
        "A short RPG game involving a young ghost who is bored and wants to live again. You travel through all of the rooms looking for objects and things you need to finish the game. In the end you discover Miss Evil! You have to defeat her to win! Good luck young gooooooost!",
      url: "https://replit.com/@BryanMellor/gooooooost?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 37,
      title: "Big Drago",
      author: "Chase Stinson",
      description:
        "Big Drago is a game where you are a newly hatched baby Drago. You must explore and eat things smaller than you to grow bigger until you become BIG Drago.",
      url: "https://replit.com/@AceInson/BigDrago?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 38,
      title: "Fancy Gem Game",
      author: "Natalie Bingham",
      description:
        "In the Fancy Gem Game you travel through different magical worlds to find hidden gems and make your bracelet fancy.",
      url: "https://replit.com/@NatalieBingham/RPG-Game-Project?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 39,
      title: "Halloween Game",
      author: "Benjamin Hopkins",
      description:
        "This project is an RPG game for Halloween. Your goal is to get candy a costume and a pillowcase to hold the candy.",
      url: "https://replit.com/@BenHopki2/Text-adventure?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 56,
      title: "The Great Bear War",
      author: "Kalob Dascomb",
      description:
        "The great bear war of 2000. It's exactly what it sounds like. It's like the great emu war but with bears.",
      url: "https://the-great-bear-war.kalobdascomb.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 58,
      title: "The Calendar Project",
      author: "Bryson Day",
      description:
        "This is a scheduling app where you can add events in the future and delete them if needed.",
      url: "https://calendar-project.demonlama.repl.co/",
      project_type: "WEB_APP",
      date_created: "2021-12-15",
    },
    {
      id: 43,
      title: "the game where you're a ghost for some reason",
      author: "Elise Hall",
      description:
        "You are a ghost who is haunting a house that is for sale. People are stupid so you don't want them to buy the house. You must kill the three of them with random objects around the house, and not get caught, or they'll ghostbust you. You can move north, east, south, or west. If you try to leave a room without killing a human, you will be caught, and have to start over. You can not carry more than one item.",
      url: "https://replit.com/@EliseHall/the-game-where-youre-a-ghost-for-some-reason?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 44,
      title: "Pretty OK Game",
      author: "Aldair Herrera and Kaysen Hansen",
      description: "Pretty ok rpg game or at least an attempt to it.",
      url: "https://replit.com/@a1d09/HULLO?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 45,
      title: "The Game",
      author: "James Brenchley",
      description: "Try to leave.",
      url: "https://replit.com/@TheFlowey27/best-rpg?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 46,
      title: "The Rat",
      author: "Gianina Montoya",
      description:
        "You are in somebody's house trying to steal an xbox and some cheese. Don't steal the bed or the TV!",
      url: "https://replit.com/@GianinaMontoya/project?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 47,
      title: "Shopping",
      author: "Elnura Muratalieva",
      description: "Shop for free. Buy some shoes!",
      url: "https://replit.com/@ElnuraMuratalie/MyGame?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 48,
      title: "No",
      author: "Caroline Poole",
      description: "No.",
      url: "https://replit.com/@CarolinePoole/RPG?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 49,
      title: "The Haunted House",
      author: "Cameron Rowberry",
      description:
        "The ghosts have captured you and won't let you leave until you have the key to unlock the front door. But be careful, ghosts are hiding in different rooms waiting for you to find them, so make sure not to disturb any of them or they will kill you.",
      url: "https://replit.com/@CameronRowberr1/The-Haunted-House?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 50,
      title: "Find Gustavo",
      author: "Eduardo Gutierrez",
      description:
        "The goal is to find Gustavo and bring him back to the living room where he can sleep.",
      url: "https://replit.com/@jk85/RPG-254?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 42,
      title: "Pool Panic",
      author: "Hudson Condie",
      description:
        "The objective of the game is to last as long as possible. Hit enemies into holes and dodge their attacks.",
      url: "https://storage.googleapis.com/merit-web-gl/pool-panic-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2021-12-15",
    },
    {
      id: 51,
      title: "Mario",
      author: "Omar Najera",
      description:
        "You can move with wasd/arrow keys, you can double jump and the fire makes you fly. There are 2 levels and you can collect fire (its different).",
      url: "https://storage.googleapis.com/merit-web-gl/mario-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2021-12-15",
    },
    {
      id: 40,
      title: "GRAPHING WEBSITE FOR DUMMIES",
      author: "Masrur Ahmed",
      description:
        "This is a website where you can put in your data as a table and it can show you different types of graphs with that data.",
      url: "https://masrur.pythonanywhere.com/",
      project_type: "WEB_APP",
      date_created: "2021-12-15",
    },
    {
      id: 52,
      title: "Roll for Sanity",
      author: "Evan Corbett",
      description:
        "Welcome to Roll for Sanity! A Dungeons and Dragons campaign where a group of fated individuals go to save the world and war against actual gods! Here, you'll be able to go over my (not entirely accurate) recap of the story and descriptions of player characters and important NPCs!",
      url: "https://final-project.evancorbett1.repl.co",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 53,
      title: "Cow",
      author: "Lexi Brindley",
      description: "Try to find the cow to win.",
      url: "https://final-project.alexisbrindley.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 54,
      title: "Hollow Site",
      author: "PJ Hakanson",
      description: "A site about Hollow Knight.",
      url: "https://finil-pwotegt.pjhakanson.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 55,
      title: "Random",
      author: "Alexa Valadez",
      description: "Just some random stuff.",
      url: "https://final-project.alexavaladez.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 57,
      title: "Rock Turtle",
      author: "AJ Carpenter",
      description: "All the stuff I made this year!",
      url: "https://rock-turtle.ajcarpenter.repl.co/home.html",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 59,
      title: "Workout App",
      author: "Eduardo Gutierrez",
      description: "Add and view workouts that you want to do.",
      url: "https://crud-20.jk85.repl.co",
      project_type: "WEB_APP",
      date_created: "2021-12-15",
    },
    {
      id: 60,
      title: "Arbiter's Archive",
      author: "Michael Dyck",
      description:
        "Add and edit characters for your D&D campaign. Keep track of notes as the Dungeon Master to track the party's progress.",
      url: "https://Arbiters-Archive.dungeonmaster42.repl.co",
      project_type: "WEB_APP",
      date_created: "2021-12-15",
    },
    {
      id: 61,
      title: "Kassidy McCoy's Site",
      author: "Kassidy McCoy",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/icommitarson/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 62,
      title: "Melany Aguilar's Site",
      author: "Melany Aguilar",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/melany/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 63,
      title: "Astrid Alcantara's Site",
      author: "Astrid Alcantara",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/mr-buckley/project-page",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 64,
      title: "Bryan Arcos-Garcia's Site",
      author: "Bryan Arcos-Garcia",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/bryan/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 65,
      title: "Emma Burris' Site",
      author: "Emma Burris",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/emma-burris/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 66,
      title: "Grant Palmer's Site",
      author: "Grant Palmer",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/david-buckley/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 67,
      title: "Game Development Skill Tree",
      author: "Tait Keck",
      description: "A site for game development skill tree.",
      url: "https://game-development.taitkeck1.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 68,
      title: "Lizbeth Diaz's Site",
      author: "Lizbeth Diaz",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/lizbethscsi/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 69,
      title: "Brigham Yeagley's Site",
      author: "Brigham Yeagley",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/view/brighams-portfolio/my-projects",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 70,
      title: "Jonathan Wright's Site",
      author: "Jonathan Wright",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/jonathans-website/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 71,
      title: "Gaming Conventions",
      author: "Dustin Marion",
      description:
        "Like any other convention you might stumble upon, gaming coventions are conventions that cover anything gaming related. For some people who are in the gaming conmunity, these events serve as a way to connect with others who enjoy the same game(s) or game genre as them. For game developers, however, these events may be used to reveal upcoming projects or even additional content to their already existing games.",
      url: "https://dustin-marion-or-final-project.dustinmarion.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 72,
      title: "Grace Parsons' Site",
      author: "Grace Parsons",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/gracielousportfolio/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 73,
      title: "David Chase's Game",
      author: "David Chase",
      description: "A project I made at Merit Academy.",
      url: "https://final-project.daveychase.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 74,
      title: "Bryce Stinson's Site",
      author: "Bryce Stinson",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/funbotwcheats/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 75,
      title: "Jocelyn Emrich's Site",
      author: "Jocelyn Emrich",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/view/jocelynmerit/my-projects?authuser=0",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 76,
      title: "Samuel Fair's Site",
      author: "Samuel Fair",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/mr-buckly/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 77,
      title: "Joaquin Gallegos' Site",
      author: "Joaquin Gallegos",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/joaquin-gallegos/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 78,
      title: "Sophia Green's Site",
      author: "Sophia Green",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/sophias-cs-portfolio/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 79,
      title: "Raini Warren's Site",
      author: "Raini Warren",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/rainis-cs/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 80,
      title: "Cassidy Wong's Site",
      author: "Cassidy Wong",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/me-myself-and-i/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 81,
      title: "Alexa Valadez's Site",
      author: "Alexa Valadez",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/alexa-valadez/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 82,
      title: "Jaxon Sutherland's Site",
      author: "Jaxon Sutherland",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/jaxon/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 83,
      title: "Kekoa Palmer's Site",
      author: "Kekoa Palmer",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/moop/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 84,
      title: "Nate Johnson's Site",
      author: "Nate Johnson",
      description: "A project I made at Merit Academy.",
      url: "https://codehs.com/sandbox/id/my-final-website-project-TAZlpr?filename=index.html",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 85,
      title: "Amritjot Khashria's Site",
      author: "Amritjot Khashria",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/view/amritjot/project?authuser=0",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 86,
      title: "Sam Leckie's Site",
      author: "Sam Leckie",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/samleckiecomputerscience/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 87,
      title: "Sabina Lopez' Site",
      author: "Sabina Lopez",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/sabina/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 88,
      title: "Kaiden Oliver's Site",
      author: "Kaiden Oliver",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/kaiden-oliver/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 89,
      title: "Meleah Carpenter's Site",
      author: "Meleah Carpenter",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/class-portfolio/home",
      project_type: "GOOGLE_SITE",
      date_created: "2021-12-15",
    },
    {
      id: 90,
      title: "Nirvana",
      author: "Jared Boyer",
      description:
        "Nirvana is an American Band founded in Aberdeen Washington is 1987. They were founded by guitarist and lead singer, Kurt Cobain and by bassist Krist Novoselic.",
      url: "https://final-project.jaredboyer.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 91,
      title: "Home Site",
      author: "Lexi Brindley",
      description:
        "Please fill out this form\r\nAre you a robot?\r\n\r\n Yes\r\n No\r\n Maybe?\r\n\r\nAre you sure?\r\n\r\n Nope\r\n Probably lol\r\n Absolutely",
      url: "https://Final-Project.alexisbrindley.repl.co",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 92,
      title: "Steven Cheng's Really Safe Site",
      author: "Steven Cheng",
      description: "THIS IS NOT A SCAM",
      url: "https://stevens-final-project.cssh.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 93,
      title: "opinion.com",
      author: "Hudson Condie",
      description: "Please provide us with all of your opinions.",
      url: "https://opinioncom.hudsoncondie.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 94,
      title: "The Great Bear War",
      author: "Kalob Dascomb",
      description:
        "The great bear war of 2000. it's exactly what it sounds. It's like the great emu war but with bears.",
      url: "https://the-great-bear-war.kalobdascomb.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 95,
      title: "Alexa's Final HTML Project",
      author: "Alexa Valadez",
      description:
        "A two-inch layer of freshly fallen snow covered the yard. Stacey peeked outside. To most, it would have been a beautiful sight worthy of taking a photo to put on Instagram. For Stacey, it meant something different. The first snow of the year brought back the witches as the fairies in the yard had to seek shelter to avoid the cold.",
      url: "https://final-project.alexavaladez.repl.co/",
      project_type: "WEBSITE",
      date_created: "2021-12-15",
    },
    {
      id: 96,
      title: "Find the Hot Chocolate",
      author: "Joseph Dyck",
      description: "Quick! Find the Hot Chocolate!",
      url: "https://codehs.com/sandbox/id/find-the-hot-chocolate-sNVOHB/run",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 97,
      title: "Sudoku Thing",
      author: "Tony Sosa",
      description: "It's a Sudoku Thing.",
      url: "https://replit.com/@sd737/sudoku-thing?embed=true",
      project_type: "REPL",
      date_created: "2021-12-15",
    },
    {
      id: 99,
      title: "Nora Allen's Site",
      author: "Nora Allen",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/nora-allens-portfolio-website/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 100,
      title: "Sidney Carlile's Site",
      author: "Sidney Carlile",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/sidney/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 101,
      title: "Addison Cash's Site",
      author: "Addison Cash",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/addison/project",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 102,
      title: "Ayla Coltharp's Site",
      author: "Ayla Coltharp",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/aylac/home",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 103,
      title: "Olivia Jay's Site",
      author: "Olivia Jay",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/olivia-jay/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 104,
      title: "Sarah Kidder's Site",
      author: "Sarah Kidder",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/sarah-kidders-webcite/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 105,
      title: "Aria Lee's Site",
      author: "Aria Lee",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/aria-lee/project-page",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 106,
      title: "Dulce Lopez's Site",
      author: "Dulce Lopez",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/about-me/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 107,
      title: "Emma Lord's Site",
      author: "Emma Lord",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/emmalordsstudentportfolio/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 108,
      title: "Preston Lord's Site",
      author: "Preston Lord",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/yourname/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 109,
      title: "Geraldine Macias' Site",
      author: "Geraldine Macias",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/geraldine/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 110,
      title: "Magdalena Marquez's Site",
      author: "Magdalena Marquez",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/magdalena/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 111,
      title: "Aiden McCabe's Site",
      author: "Aiden McCabe",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/aiden-portfolio/prajects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 112,
      title: "Mary Moody's Site",
      author: "Mary Moody",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/mary-moody/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 113,
      title: "Fiona Morkel's Site",
      author: "Fiona Morkel",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/fionaswebsite/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 114,
      title: "Eli Nichols' Site",
      author: "Eli Nichols",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/eli-nichols/home",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 115,
      title: "Xochitl Ramos' Site",
      author: "Xochitl Ramos",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/xochitl/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 116,
      title: "Mellissa Rose's Site",
      author: "Mellissa Rose",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/computer-science-portfolio/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 117,
      title: "Joanna Ruiz's Site",
      author: "Joanna Ruiz",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/about-me-joanna/project",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 118,
      title: "Raul Ruiz's Site",
      author: "Raul Ruiz",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/oscars-website/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 119,
      title: "Perry Sutherland's Site",
      author: "Perry Sutherland",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/perry-sutherland/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 120,
      title: "Fernanda Teran's Site",
      author: "Fernanda Teran",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/fernanda/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 121,
      title: "Alex Teran's Site",
      author: "Alex Teran",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/alex-t/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 122,
      title: "Madeline West's Site",
      author: "Madeline West",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/maddy-w/home",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 123,
      title: "Aster Williams' Site",
      author: "Aster Williams",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/aster/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 124,
      title: "Carlee Wooten's Site",
      author: "Carlee Wooten",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/carleewooten/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-16",
    },
    {
      id: 125,
      title: "Obbjumper",
      author: "Evan Corbett",
      description: "A game about a little guy jumping on big objects.",
      url: "https://storage.googleapis.com/merit-web-gl/obbjumper-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-16",
    },
    {
      id: 126,
      title: "Platformer",
      author: "Conner Young",
      description:
        "Jump around collecting coins while making your way through difficult levels to get to the end!",
      url: "https://storage.googleapis.com/merit-web-gl/platformer-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-16",
    },
    {
      id: 164,
      title: "Battle Beans",
      author: "PJ Hakanson and AJ Carpenter",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/battle-beans-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-14",
    },
    {
      id: 128,
      title: "Diego Axe Collector",
      author: "Brodee Dixon and Diego Sanchez",
      description:
        "in our game you must navigate through the levels collecting axes and reach the door to the next level.",
      url: "https://storage.googleapis.com/merit-web-gl/diego-axe-collector-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-16",
    },
    {
      id: 129,
      title: "Basketball Win",
      author: "Davey Chase",
      description:
        "A fun 1 v 1 basketball game were you pick your favorite player and play your friends. Player 1: Arrows; Player 2: WASD.",
      url: "https://storage.googleapis.com/merit-web-gl/basketball-win-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-16",
    },
    {
      id: 167,
      title: "Maze Runner",
      author: "Evan Parra and Michael Malone",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/maze-runner-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-14",
    },
    {
      id: 171,
      title: "The Game of All Time",
      author: "James Brenchley",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/the-game-of-all-time-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-14",
    },
    {
      id: 132,
      title: "Race Game",
      author: "Lucas Cornaby",
      description:
        "A project I made at Merit Academy. This is a racing game where you try to find your way to the end as fast and you can, then beat that speed.",
      url: "https://storage.googleapis.com/merit-web-gl/race-game-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-16",
    },
    {
      id: 174,
      title: "Hardcore Parkour",
      author: "Koby Jones",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/koby-game-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-19",
    },
    {
      id: 135,
      title: "JamChat",
      author: "Masrur Ahmed",
      description:
        "JamChat is an online chat app where you can sign in with your Google account and write messages. It is one big group chat where everyone can talk with everyone. The website is made with React and the data is stored in Google Firebase.",
      url: "https://jamchat.netlify.app",
      project_type: "WEB_APP",
      date_created: "2022-05-17",
    },
    {
      id: 136,
      title: "Pokemans II: The Reckoning",
      author: "James Brenchley",
      description:
        "This is a program that can bring up basic data on any pokemon entry. To chose which pokemon you want info on, you just put in their pokedex entry number. After I got the code functioning, I added things to make it more asthetically pleasing like a small pokeball animation next to the search bar, and a colored background based on what type they are.",
      url: "https://pokemans-ii-the-reckoning.theflowey27.repl.co/",
      project_type: "WEB_APP",
      date_created: "2022-05-17",
    },
    {
      id: 140,
      title: "Button Causer",
      author: "Elise Hall",
      description:
        "A button has mysteriously appeared. When you press it, by some amazing coincidence, something happens at that exact moment. Keep pressing the button for more things to happen.",
      url: "https://button-causer.elisehall.repl.co/",
      project_type: "WEB_APP",
      date_created: "2022-05-17",
    },
    {
      id: 143,
      title: "Chat Bot",
      author: "Benjamin Hopkins",
      description:
        "You can chat with this robot with all kinds of different greetings and ask it numerous basic questions like what its doing or what its favorite food is. it will give you instructions on what and how to rephase things so it can find a proper response.",
      url: "https://chat-bot.benhopki2.repl.co/",
      project_type: "REPL",
      date_created: "2022-05-17",
    },
    {
      id: 144,
      title: "Buckets, Man",
      author: "Kasey Finch",
      description: "CLICK THE BUCKETS CLICK THE BUCKETS CLICK THE BUCKETS",
      url: "https://storage.googleapis.com/merit-web-gl/buckets-man-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-17",
    },
    {
      id: 137,
      title: "Fun Snake Game",
      author: "Marilyn Emrich",
      description:
        "This is a snake game - you know, that old arcade game where you try to get a snake to eat as much food as possible and try not to run into yourself, which is difficult since you get longer every time you eat! The purpose of this code is to have fun. Use the arrow keys to move. Also, if you go backwards or run into a wall, you will die.",
      url: "https://my-actual-explore-project.marilynemrich.repl.co/",
      project_type: "REPL",
      date_created: "2022-05-17",
    },
    {
      id: 138,
      title: "Snake",
      author: "Draeden Griffith",
      description:
        "In my program I showcase several different things, like for example my first one was I coded the food.",
      url: "https://snake.draedengriffith.repl.co/",
      project_type: "REPL",
      date_created: "2022-05-17",
    },
    {
      id: 139,
      title: "Flappy Bird",
      author: "Peggy Chou",
      description:
        "This game is the Flappy bird, and this game is easy to play, you just have to press the space key and then you can play, and when you died you just have to press right mouse button.",
      url: "https://final-project.peiyuchou.repl.co/",
      project_type: "REPL",
      date_created: "2022-05-17",
    },
    {
      id: 141,
      title: "Pitbull Snake",
      author: "Ava Hatfield",
      description:
        "In my game I coded it so pitbull would play while you played the snake game. The variable snake is the most important variable because without it there would be no snake and the game would not work at all.",
      url: "https://snake.avahatfield.repl.co/",
      project_type: "REPL",
      date_created: "2022-05-17",
    },
    {
      id: 142,
      title: "OMG Why Snake",
      author: "Aldair Herrara",
      description: "You a snake.",
      url: "https://omg-why.aldairherrera.repl.co/",
      project_type: "REPL",
      date_created: "2022-05-17",
    },
    {
      id: 145,
      title: "Frogger",
      author: "Gianina Montoya",
      description:
        "This is a mini game of frogger. In the first section there is cars that you have to avoid. Then you need to jump on the logs and avoid the water(The water is gray because i wanted it to be). Once you reach the end, you win but I didn't code that part in so just imagine there's big words on the screen that say \"you win.\" if you want to restart then just hit into a car or jump in the water.",
      url: "https://replit.com/@GianinaMontoya/Final-project?embed=true",
      project_type: "REPL",
      date_created: "2022-05-17",
    },
    {
      id: 146,
      title: "Unicorn",
      author: "Elnura Muratalieva",
      description:
        "In this game we have unicorn and trains. The dinosaur have to jump over the trains. If you will not be able to jump and you will hit the train you lose.",
      url: "https://dinosaur.elnuramuratalie.repl.co/",
      project_type: "REPL",
      date_created: "2022-05-17",
    },
    {
      id: 147,
      title: "Doodle Thing",
      author: "Cameron Rowberry",
      description:
        "It is a game where you change the color and size of the brush to draw using your mouse. This game has multiple buttons that you can click to either draw, or change your brush size. You click and hold the mouse to draw.",
      url: "https://doodle-thing.cameronrowberr1.repl.co/",
      project_type: "WEB_APP",
      date_created: "2022-05-17",
    },
    {
      id: 148,
      title: "Battlesnake",
      author: "Thomas Thoebald",
      description:
        "Battlesnake! A game I thought up in a spirit of boredom after finishing an earlier snake project which involved adding a PvP element to the game with another snake, competing for the food, and trying to avoid the other snake.",
      url: "https://battlesnake.thomasthatcher.repl.co/",
      project_type: "REPL",
      date_created: "2022-05-17",
    },
    {
      id: 149,
      title: "Oscar Hernandez's Site",
      author: "Oscar Hernandez",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/raul/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-18",
    },
    {
      id: 150,
      title: "Duck Game",
      author: "Gillian Glidewell",
      description: "A project I made at Merit Academy.",
      url: "https://duck-game.cryingduckling.repl.co",
      project_type: "REPL",
      date_created: "2022-05-18",
    },
    {
      id: 151,
      title: "Emma Hjorth's Site",
      author: "Emma Hjorth",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/emma-hjorth/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-18",
    },
    {
      id: 152,
      title: "Muriel Markham's Site",
      author: "Muriel Markham",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/computerscience/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-18",
    },
    {
      id: 153,
      title: "John Garrido's Site",
      author: "John Garrido",
      description: "A project I made at Merit Academy.",
      url: "https://sites.google.com/meritknights.com/john-garrido/projects",
      project_type: "GOOGLE_SITE",
      date_created: "2022-05-18",
    },
    {
      id: 154,
      title: "Enguzu Landscaping",
      author: "Eduardo Gutierrez",
      description: "A website for my landscaping business.",
      url: "https://www.enguzulandscaping.com/",
      project_type: "WEBSITE",
      date_created: "2022-05-18",
    },
    {
      id: 155,
      title: "Rage Parkour",
      author: "Dustin Powell",
      description:
        "A simple rage parkour game with controls changing for each level.",
      url: "https://storage.googleapis.com/merit-web-gl/rage-parkour-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-18",
    },
    {
      id: 156,
      title: "3D Parkour Game",
      author: "Dustin Marion",
      description:
        "Welcome to 3D Parkour Game! Get to the giant ball atop of one of the rooftops to win.\r\n\r\nUse WASD to move, use Shift to sprint, use Space to jump, and use the mouse to move the camera.\r\n\r\n(This game is best played in Fullscreen).",
      url: "https://storage.googleapis.com/merit-web-gl/3d-parkour-game-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-18",
    },
    {
      id: 127,
      title: "Astioed",
      author: "Zarin Brown and Grant Cornaby",
      description:
        "You are a ship but you are stuck in space so now you have to get to the moon then the earth. You use w,a,s and d to move you can press two buttons to move in a diagonal direction. There is an arrow above you that tells you where the end is. This is a hard game. If you rage don't break your computer we are not responsible for that.",
      url: "https://storage.googleapis.com/merit-web-gl/astioed-v1.0.2/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-16",
    },
    {
      id: 134,
      title: "Dragon Game",
      author: "Grant Palmer",
      description: "Don't touch the clouds.",
      url: "https://storage.googleapis.com/merit-web-gl/dragon-game-v1.0.1/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-16",
    },
    {
      id: 131,
      title: "Dugin' Proof of Concept",
      author: "Ryan Cunningham",
      description:
        "A project I made at Merit Academy.\r\nThe descent into one's own mind... who knows how the brain handles the subconscious?",
      url: "https://storage.googleapis.com/merit-web-gl/dugin-poc-v1.2.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-16",
    },
    {
      id: 133,
      title: "Worm Game",
      author: "Alex Bills",
      description:
        "A game where you are a worm and you have to go around the levels and eat the dirt while avoiding all the enemies.",
      url: "https://storage.googleapis.com/merit-web-gl/worm-game-v1.0.1/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-16",
    },
    {
      id: 157,
      title: "Robo Run",
      author: "AJ Carpenter",
      description:
        "A platformer where you're a robot. Use WASD or arrow keys to move.",
      url: "https://storage.googleapis.com/merit-web-gl/robo-run-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-18",
    },
    {
      id: 130,
      title: "Darkness",
      author: "Amy Salas",
      description:
        "You are in darkness and you click and then stuff appears! But be careful because you can die.",
      url: "https://storage.googleapis.com/merit-web-gl/darkness-v1.0.5/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-16",
    },
    {
      id: 158,
      title: "Degenerate Game HAHA Funny",
      author: "Morgan Bergstrand",
      description: "Play this game haha",
      url: "https://storage.googleapis.com/merit-web-gl/degenerate-game-haha-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-18",
    },
    {
      id: 165,
      title: "Buggy Boi Game",
      author: "Elise Hall",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/buggy-boi-game-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-14",
    },
    {
      id: 172,
      title: "Operation Exadis",
      author: "Nathan Reedy",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/operation-exadis-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-14",
    },
    {
      id: 175,
      title: "The MAZE",
      author: "Gianina Montoya",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/the-maze-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-21",
    },
    {
      id: 168,
      title: "Haunted Mansion",
      author: "Gordon Chase and Aiden Herlehy",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/haunted-mansion-v1.1.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-14",
    },
    {
      id: 159,
      title: "V!E!L!O!C!I!T!Y",
      author: "Brennon Jones",
      description:
        "Velocity is a game where you go boom. Mouse to shoot and arrows to move.",
      url: "https://storage.googleapis.com/merit-web-gl/velocity-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-18",
    },
    {
      id: 160,
      title: "Your in Space",
      author: "Ian Smith",
      description: "You are in space!",
      url: "https://storage.googleapis.com/merit-web-gl/your-in-space-v1.0.1/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-18",
    },
    {
      id: 161,
      title: "8-Ball App",
      author: "Chase Stinson",
      description: "Decide your destiny!",
      url: "https://magic-8-ball.aceinson.repl.co/",
      project_type: "WEB_APP",
      date_created: "2022-05-18",
    },
    {
      id: 162,
      title: "The Worst Project Ever",
      author: "Bradley Fogg",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/the-worst-project-ever-v1.0.1/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-18",
    },
    {
      id: 163,
      title: "RPG Game",
      author: "Evan Parra",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/rpg-game-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-05-18",
    },
    {
      id: 169,
      title: "Galaxy Goop",
      author: "Miles Petersen",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/galaxy-goop-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-14",
    },
    {
      id: 173,
      title: "Jumping Box",
      author: "Diego Sanchez",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/jumping-box-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-14",
    },
    {
      id: 166,
      title: "Uh-Oh Maze",
      author: "Bryce Stinson and Cameron Rowberry",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/uh-oh-maze-v1.1.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-14",
    },
    {
      id: 170,
      title: "HII",
      author: "Peter Moyer and Lorelei Huyck",
      description: "A project I made at Merit Academy.",
      url: "https://storage.googleapis.com/merit-web-gl/hii-v1.1.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2022-12-14",
    },
    {
      id: 200,
      title: "Chinese Repair Shop",
      author: "Conner Young",
      description: "Repair them vases and such. Click to do stuff.",
      url: "https://storage.googleapis.com/merit-web-gl/chinese-repair-shop-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2023-05-22",
    },
    {
      id: 201,
      title: "Grant Tower Defense",
      author: "Ian Smith",
      description: "Defend your land from an onslaught of Grants.",
      url: "https://gtd.pages.dev",
      project_type: "WEBGL_GAME",
      date_created: "2023-05-22",
    },
    {
      id: 202,
      title: "ChessTower",
      author: "Hudson Condie",
      description:
        "A game where you get skills. It is an auto-battler so uh I don't know uh.",
      url: "https://storage.googleapis.com/merit-web-gl/chesstower-v1.0.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2023-05-22",
    },
    {
      id: 203,
      title: "Jello Parkour",
      author: "Elise Hall",
      description: "You a Jello. Collect the fruits to win.",
      url: "https://storage.googleapis.com/merit-web-gl/jello-parkour-v1.1.0/index.html",
      project_type: "WEBGL_GAME",
      date_created: "2023-05-22",
    },
  ]);
}
